FROM debian:bullseye-slim

WORKDIR /workspace
RUN apt update
RUN apt install git zsh curl nano make gcc wget build-essential procps -y
RUN sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" -y
RUN echo "zsh" >> ~/.bashrc 
RUN sh -c "$(curl -fsSL https://deb.nodesource.com/setup_current.x)" -y
RUN apt install nodejs -y
RUN npm install -g yarn

