version: '3.9'
services:
  jslib:
    build:
      dockerfile: Dockerfile.dev
    command: /bin/sh -c "while sleep 1000; do :; done"
    volumes:
      - .:/workspace:cached
      - ~/.ssh:/root/.ssh
